#21. testando hierarquia
print("\nTESTABNDO HIERARQUIA\n")
print("\n12 + 5/2 é igual a: ", 12 + 5/2)
print("\nÉ diferente de (12 + 5)/2 que é igual a: ",(12 + 5)/2, " logo ** tem HIERARQUIA MAIOR \ndo que + ou -")
print("\n\n64** 1/4 é igual a: ", 64**1/4)
print("\nÉ DIFERENTE de 64**(1/4)que é igual a: ", 64**(1/4), " logo ** tem HIERARQUIA MAIOR \ndo que * ou /")
print("\n\n3*7 % 5 é igual a: ", 3*7 % 5)
print("\nÉ DIFERENTE de (3 * 7) % 5 que é igual a: ",(3 * 7) % 5, "logo % tem HIERARQUIA MAIOR do que: * ")
print("\n\n3 * 7 div 5 é igual a: ", 3*7 / 5)
print("\nÉ IGUAL a (3 * 7) div. 5 : ", (3 * 7) / 5," logo div tem a MESMA HIERARQUIA \nda * ou / ")
print("FROM SH4RKVICC")