#35.leia o nome, endereco e telefone e imprimir (input)
n = input("Insira seu nome: ")
e = input("Insira seu endereço: ")
t = input("Insira seu telefone: ")
print(f"Nome: {n}.\nEndereço: {e}.\nTelefone: {t}.")