#49. nome
n = input("Insira seu nome completo: ")
print("\nTodo o nome: ", n)
print("\nPrimeiro Caractere: ", n[0])
print("\nÚltimo Caractere: ", n[-1])
print("\nPrimeiro ao terceiro caractere: ", n[:3])
print("\nQuarto Caractere: ", n[3])
print("\nTodos menos o primeiro: ", n[1:])
print("\nOs dois ultimos: ", n[-2:])
print("FROM SH4RKVICC")